##### returns the matrix exponential discretization of the system matrix, deconstructed as one dimensional array
#
### input 1 : system matrix deconstructed as one dimensional array
#
# [[1, 2],
#  [3, 4],
#  [5, 6]]
#
# [1, 2, 3, 4, 5, 6]
#
### input 2 : height or row count of system matrix
#
# 1) [[*],
# 2)  [*],
# 3)  [*]]
#
# height = 3 rows
#
### input 3 : width or column count of system matrix
#
#   1) 2)
#  [*, *]
#
# width = 2 columns
#
### input 4 : time step of the discretization
#
### input 5 : step number in taylor series expansion
#
### output 1 : matrix deconstructed as one dimensional array
#
#####
float64[] system_matrix
int64 n
int64 m
float64 dt
int64 step
---
float64[] result
